services:
  mongodb:
    image: mongo:3
    container_name: mongodb
    stop_grace_period: 60s
    user: "508:508"
    command: ["--dbpath","/data/db/db"]
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    volumes:
      - omada-data:/data/db
    tmpfs:
      - /data/configdb
    networks:
      - omada

  omada-controller:
    #image: mbentley/omada-controller:beta
    image: mbentley/omada-controller:5.15
    container_name: omada-controller
    stop_grace_period: 60s
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    ports:
      - "8088:8088"
      - "8043:8043"
      - "8843:8843"
      - "19810:19810/udp"
      - "27001:27001/udp"
      - "29810:29810/udp"
      - "29811-29817:29811-29817"
    environment:
      MONGO_EXTERNAL: "true"
      EAP_MONGOD_URI: "mongodb://mongodb:27017/omada"
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    networks:
      - omada

networks:
  omada:
    driver: bridge

volumes:
  omada-data:
    external: true
  omada-logs:
    external: true
