services:
  bootstrap:
    image: busybox:latest
    container_name: omada-bootstrap
    command:
      - sh
      - -c
      - |
        cat > /init/omada.js << 'EOF'
        db.createUser(
          {
            user: "omada",
            pwd: "0m4d4",
            roles: [
              {
                role: "readWrite",
                db: "omada"
              },
              {
                role: "dbOwner",
                db: "omada"
              },
              {
                role: "readWrite",
                db: "omada_data"
              },
              {
                role: "dbOwner",
                db: "omada_data"
              }
            ]
          }
        );
        EOF
        echo "omada.js created successfully"
    volumes:
      - omada-init-scripts:/init

  mongodb:
    image: mongo:4
    container_name: mongodb
    stop_grace_period: 60s
    depends_on:
      bootstrap:
        condition: service_completed_successfully
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: omada
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    volumes:
      - omada-mongo-config:/data/configdb
      - omada-mongo-data:/data/db
      - omada-init-scripts:/docker-entrypoint-initdb.d/omada.js
    networks:
      - omada

  omada-controller:
    #image: mbentley/omada-controller:beta
    image: mbentley/omada-controller:5.15
    container_name: omada-controller
    stop_grace_period: 60s
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    ports:
      - "8088:8088"
      - "8043:8043"
      - "8843:8843"
      - "19810:19810/udp"
      - "27001:27001/udp"
      - "29810:29810/udp"
      - "29811-29817:29811-29817"
    environment:
      MONGO_EXTERNAL: "true"
      EAP_MONGOD_URI: "mongodb://omada:0m4d4@mongodb:27017/omada"
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    networks:
      - omada

networks:
  omada:
    driver: bridge

volumes:
  omada-mongo-config:
  omada-mongo-data:
  omada-init-scripts:
  omada-data:
  omada-logs:
